-- Insert perspective presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Eye-Level', 'Perspective', 'Natural viewing angle at human eye level, creating a sense of normalcy and connection'),
    ('Worm''s Eye View', 'Perspective', 'Extreme low angle looking up, creating dramatic and imposing compositions'),
    ('Bird''s Eye View', 'Perspective', 'High angle looking down, providing an overview of the scene'),
    ('Overhead Shot', 'Perspective', 'Directly above the subject, creating abstract and geometric compositions'),
    ('Low Angle', 'Perspective', 'Looking up at the subject, emphasizing power and dominance'),
    ('High Angle', 'Perspective', 'Looking down at the subject, creating a sense of vulnerability'),
    ('Dutch Angle', 'Perspective', 'Tilted camera angle creating tension and unease'),
    ('Close-Up', 'Perspective', 'Framing that focuses on a subject''s face or important detail'),
    ('Extreme Close-Up', 'Perspective', 'Very tight framing on a specific detail or feature'),
    ('Medium Shot', 'Perspective', 'Framing that shows the subject from waist up'),
    ('Wide Shot', 'Perspective', 'Full body view of the subject with surrounding environment'),
    ('Extreme Wide Shot', 'Perspective', 'Establishing shot showing the entire scene and context'),
    ('Over-the-Shoulder Shot', 'Perspective', 'View from behind a subject looking at another subject'),
    ('POV Shot', 'Perspective', 'Point of view perspective showing what a character sees'),
    ('First-Person Perspective', 'Perspective', 'View through the eyes of the subject'),
    ('Third-Person Perspective', 'Perspective', 'View from an external observer''s position'),
    ('Isometric View', 'Perspective', 'Technical drawing perspective with equal measurements'),
    ('Top-Down View', 'Perspective', 'Direct overhead perspective with clear spatial relationships'),
    ('Side View', 'Perspective', 'Profile view showing the subject from the side'),
    ('Front View', 'Perspective', 'Direct head-on view of the subject'),
    ('Rear View', 'Perspective', 'View from behind the subject'),
    ('Angled View', 'Perspective', 'Diagonal perspective creating dynamic composition'),
    ('3/4 View', 'Perspective', 'View showing three-quarters of the subject'),
    ('Fisheye Lens', 'Perspective', 'Extreme wide-angle view with barrel distortion'),
    ('Macro Perspective', 'Perspective', 'Extreme close-up view of small subjects'),
    ('Tilt-Shift Effect', 'Perspective', 'Selective focus creating miniature effect'),
    ('Panoramic View', 'Perspective', 'Wide horizontal view capturing expansive scenes'),
    ('Follow Shot', 'Perspective', 'Moving camera following the subject'),
    ('Static Shot', 'Perspective', 'Fixed camera position with no movement'),
    ('Zoom-In Effect', 'Perspective', 'Gradual magnification of the subject'),
    ('Zoom-Out Effect', 'Perspective', 'Gradual reduction of the subject'),
    ('Bokeh-Focused Shot', 'Perspective', 'Shallow depth of field with blurred background'),
    ('Depth of Field Emphasis', 'Perspective', 'Selective focus drawing attention to specific elements'),
    ('Cinematic Framing', 'Perspective', 'Professional film composition with balanced elements'),
    ('Rule of Thirds', 'Perspective', 'Composition following the rule of thirds grid'); 