-- Insert artist presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Van Gogh', 'Artists', 'Swirling brushstrokes, post-impressionist style with vibrant colors and emotional depth'),
    ('Studio Ghibli', 'Artists', 'Soft, storybook fantasy aesthetic with anime influence and whimsical atmosphere'),
    ('H.R. Giger', 'Artists', 'Biomechanical horror and alien surrealism with dark, organic-mechanical fusion'),
    ('Pablo Picasso', 'Artists', 'Cubist style with abstract forms and distorted anatomy, breaking traditional perspective'),
    ('Greg Rutkowski', 'Artists', 'Epic fantasy scenes with highly detailed digital painting and dramatic lighting'),
    ('Leonardo da Vinci', 'Artists', 'Renaissance realism with soft lighting and precise anatomical accuracy'),
    ('Claude Monet', 'Artists', 'Impressionist style capturing light play and atmospheric effects in nature scenes'),
    ('Salvador Dalí', 'Artists', 'Surreal, dreamlike imagery with melting forms and impossible perspectives'),
    ('Frida Kahlo', 'Artists', 'Symbolic portraiture with bold colors and deep emotional intensity'),
    ('Andy Warhol', 'Artists', 'Pop art style with bold color blocking and celebrity culture references'),
    ('Alphonse Mucha', 'Artists', 'Art Nouveau elegance with flowing floral decorative lines and ethereal figures'),
    ('Jean-Michel Basquiat', 'Artists', 'Expressive street art style with abstract graffiti elements and raw energy'),
    ('Yayoi Kusama', 'Artists', 'Signature polka dots and psychedelic patterns with obsessive repetition'),
    ('Zdzisław Beksiński', 'Artists', 'Dystopian surrealism with nightmare landscapes and haunting atmosphere'),
    ('Jackson Pollock', 'Artists', 'Abstract expressionism with dynamic splatter painting and energetic composition'),
    ('Rembrandt', 'Artists', 'Dramatic Baroque lighting with deep shadows and realistic portraiture'),
    ('Hokusai', 'Artists', 'Traditional Japanese woodblock print style with iconic wave patterns'),
    ('Edward Hopper', 'Artists', 'Moody Americana with cinematic loneliness and dramatic lighting'),
    ('Alex Ross', 'Artists', 'Hyper-realistic comic book style with dramatic superhero compositions'),
    ('Loish', 'Artists', 'Digital femininity with soft painterly portraits and warm color palettes'),
    ('Magritte', 'Artists', 'Surrealist symbolism with visual paradoxes and thought-provoking imagery'),
    ('James Gurney', 'Artists', 'Dinotopia realism with detailed fantasy illustration and natural lighting'),
    ('Takeshi Obata', 'Artists', 'Manga precision with dramatic compositions and detailed character design'),
    ('Caravaggio', 'Artists', 'Extreme chiaroscuro with dramatic tension and theatrical lighting'),
    ('Moebius', 'Artists', 'Clean sci-fi line art with surreal fantasy elements and intricate world-building'); 