-- Insert camera presets
INSERT INTO public.presets (name, category, content) VALUES
    ('85mm f/1.4 Portrait Lens', 'Cameras', 'Classic portrait look with sharp subject focus and creamy background blur (shallow depth of field)'),
    ('35mm Film Camera', 'Cameras', 'Documentary style with environmental portraits and authentic film grain'),
    ('50mm f/1.8 (Nifty Fifty)', 'Cameras', 'Natural perspective with slightly shallow depth of field, perfect for everyday photography'),
    ('24mm Wide-Angle Lens', 'Cameras', 'Landscape and architecture photography with wide perspective and slight distortion'),
    ('16mm Ultra-Wide Lens', 'Cameras', 'Extreme wide angle with strong barrel distortion, ideal for action scenes'),
    ('105mm Telephoto Lens', 'Cameras', 'Close-up photography without distortion, perfect for fashion or wildlife'),
    ('200mm Zoom Lens', 'Cameras', 'Distant subject capture with compressed depth and surveillance-like perspective'),
    ('600mm Super Telephoto', 'Cameras', 'Wildlife and sports photography with extreme detail at long distances'),
    ('Macro Lens (100mm f/2.8)', 'Cameras', 'Extreme close-up capability for insects, textures, and tiny details'),
    ('Tilt-Shift Lens', 'Cameras', 'Miniature city effect with architectural straight lines and selective focus'),
    ('Fisheye Lens (8mm)', 'Cameras', 'Spherical distortion with 180° field of view for creative perspectives'),
    ('Drone Camera (Top-Down)', 'Cameras', 'Bird''s-eye perspective perfect for landscape mapping and aerial views'),
    ('GoPro Wide Lens', 'Cameras', 'Action camera look with first-person extreme sports perspective'),
    ('Vintage Polaroid Camera', 'Cameras', 'Instant film aesthetic with nostalgic and lo-fi characteristics'),
    ('Medium Format Camera', 'Cameras', 'Ultra-high detail capture, commonly used in fashion and editorial shoots'),
    ('Large Format Camera', 'Cameras', 'Technical photography with extreme resolution and precise control'),
    ('Smartphone Camera', 'Cameras', 'Casual realism with common angles and limited depth of field control'),
    ('DSLR (Full Frame)', 'Cameras', 'Standard digital photography with realistic representation'),
    ('Mirrorless Camera', 'Cameras', 'Lightweight system producing clean, modern imagery'),
    ('Security Camera (CCTV)', 'Cameras', 'Surveillance aesthetic with low perspective and desaturated colors'),
    ('Underwater Camera', 'Cameras', 'Aquatic environment capture with filtered light and soft contrast'),
    ('Infrared Camera', 'Cameras', 'False-color imaging with surreal heat-map or ghostlike visuals'),
    ('Night Vision Camera', 'Cameras', 'Military-style green glow or enhanced low-light rendering'),
    ('Thermal Camera', 'Cameras', 'Color-coded heat vision creating surreal and abstract imagery'),
    ('Pinhole Camera', 'Cameras', 'Soft focus with vintage DIY aesthetic and unique light leaks'),
    ('Disposable Film Camera', 'Cameras', 'Grainy, low-resolution images with 90s nostalgic vibe'),
    ('360° Camera', 'Cameras', 'Wraparound environment capture for immersive scene representation'),
    ('Cinema Camera (RED/Alexa)', 'Cameras', 'High-end film production quality with exceptional dynamic range'),
    ('Webcam View', 'Cameras', 'Flat angle perspective with low resolution and casual online aesthetic'),
    ('Camcorder (90s DV Style)', 'Cameras', 'VHS textures with dated autofocus and retro nostalgia'); 