-- Add interior design presets
INSERT INTO public.presets (name, category, content, modes) VALUES
-- Room Type
('Living Room', 'Room Type', '{"type": "text", "description": "Design for living room spaces"}', ARRAY['interior']),
('Bedroom', 'Room Type', '{"type": "text", "description": "Design for bedroom spaces"}', ARRAY['interior']),
('Kitchen', 'Room Type', '{"type": "text", "description": "Design for kitchen spaces"}', ARRAY['interior']),
('Bathroom', 'Room Type', '{"type": "text", "description": "Design for bathroom spaces"}', ARRAY['interior']),
('Office', 'Room Type', '{"type": "text", "description": "Design for office spaces"}', ARRAY['interior']),
('Dining Room', 'Room Type', '{"type": "text", "description": "Design for dining room spaces"}', ARRAY['interior']),
('Walk-in Closet', 'Room Type', '{"type": "text", "description": "Design for walk-in closet spaces"}', ARRAY['interior']),

-- Style
('Modern', 'Style', '{"type": "text", "description": "Contemporary modern design style"}', ARRAY['interior']),
('Minimalist', 'Style', '{"type": "text", "description": "Clean and minimal design style"}', ARRAY['interior']),
('Scandinavian', 'Style', '{"type": "text", "description": "Nordic-inspired design style"}', ARRAY['interior']),
('Industrial', 'Style', '{"type": "text", "description": "Industrial and urban design style"}', ARRAY['interior']),
('Bohemian', 'Style', '{"type": "text", "description": "Eclectic and artistic design style"}', ARRAY['interior']),
('Farmhouse', 'Style', '{"type": "text", "description": "Rustic farmhouse design style"}', ARRAY['interior']),
('Art Deco', 'Style', '{"type": "text", "description": "1920s art deco design style"}', ARRAY['interior']),
('Japandi', 'Style', '{"type": "text", "description": "Japanese-Scandinavian fusion style"}', ARRAY['interior']),
('Coastal', 'Style', '{"type": "text", "description": "Beach-inspired design style"}', ARRAY['interior']),

-- Materials
('Concrete', 'Materials', '{"type": "text", "description": "Raw concrete material style"}', ARRAY['interior']),
('Marble', 'Materials', '{"type": "text", "description": "Luxurious marble material style"}', ARRAY['interior']),
('Light Wood', 'Materials', '{"type": "text", "description": "Light wood material style"}', ARRAY['interior']),
('Dark Wood', 'Materials', '{"type": "text", "description": "Dark wood material style"}', ARRAY['interior']),
('Reclaimed Wood', 'Materials', '{"type": "text", "description": "Reclaimed wood material style"}', ARRAY['interior']),
('Exposed Brick', 'Materials', '{"type": "text", "description": "Exposed brick material style"}', ARRAY['interior']),
('Painted Brick', 'Materials', '{"type": "text", "description": "Painted brick material style"}', ARRAY['interior']),
('Brushed Steel', 'Materials', '{"type": "text", "description": "Brushed steel material style"}', ARRAY['interior']),
('Copper', 'Materials', '{"type": "text", "description": "Copper material style"}', ARRAY['interior']),
('Frosted Glass', 'Materials', '{"type": "text", "description": "Frosted glass material style"}', ARRAY['interior']),
('Clear Glass', 'Materials', '{"type": "text", "description": "Clear glass material style"}', ARRAY['interior']),

-- Color Palette
('Neutral Tones', 'Color Palette', '{"type": "text", "description": "Neutral color palette"}', ARRAY['interior']),
('Monochrome', 'Color Palette', '{"type": "text", "description": "Monochrome color palette"}', ARRAY['interior']),
('Earthy', 'Color Palette', '{"type": "text", "description": "Earthy color palette"}', ARRAY['interior']),
('Warm', 'Color Palette', '{"type": "text", "description": "Warm color palette"}', ARRAY['interior']),
('Cool', 'Color Palette', '{"type": "text", "description": "Cool color palette"}', ARRAY['interior']),
('Bold Accent Colors', 'Color Palette', '{"type": "text", "description": "Bold accent color palette"}', ARRAY['interior']),

-- Lighting
('Natural Daylight', 'Lighting', '{"type": "text", "description": "Natural daylight lighting style"}', ARRAY['interior']),
('Ambient Lighting', 'Lighting', '{"type": "text", "description": "Ambient lighting style"}', ARRAY['interior']),
('Pendant Lights', 'Lighting', '{"type": "text", "description": "Pendant light fixtures"}', ARRAY['interior']),
('LED Strip Lighting', 'Lighting', '{"type": "text", "description": "LED strip lighting style"}', ARRAY['interior']),
('Recessed Ceiling Lights', 'Lighting', '{"type": "text", "description": "Recessed ceiling lighting"}', ARRAY['interior']),
('Candlelight Mood', 'Lighting', '{"type": "text", "description": "Candlelight mood lighting"}', ARRAY['interior']),

-- Perspective
('Eye-level', 'Perspective', '{"type": "text", "description": "Eye-level perspective"}', ARRAY['interior']),
('Wide-angle', 'Perspective', '{"type": "text", "description": "Wide-angle perspective"}', ARRAY['interior']),
('Top-down', 'Perspective', '{"type": "text", "description": "Top-down plan view perspective"}', ARRAY['interior']),
('Isometric', 'Perspective', '{"type": "text", "description": "Isometric perspective"}', ARRAY['interior']),
('Corner Shot', 'Perspective', '{"type": "text", "description": "Corner shot perspective"}', ARRAY['interior']),

-- Mood
('Cozy', 'Mood', '{"type": "text", "description": "Cozy and comfortable mood"}', ARRAY['interior']),
('Luxurious', 'Mood', '{"type": "text", "description": "Luxurious and elegant mood"}', ARRAY['interior']),
('Bright and Airy', 'Mood', '{"type": "text", "description": "Bright and airy mood"}', ARRAY['interior']),
('Warm and Intimate', 'Mood', '{"type": "text", "description": "Warm and intimate mood"}', ARRAY['interior']),
('Sleek and Futuristic', 'Mood', '{"type": "text", "description": "Sleek and futuristic mood"}', ARRAY['interior']),

-- Decor
('Wall Art', 'Decor', '{"type": "text", "description": "Wall art decor elements"}', ARRAY['interior']),
('Indoor Plants', 'Decor', '{"type": "text", "description": "Indoor plant decor elements"}', ARRAY['interior']),
('Rugs', 'Decor', '{"type": "text", "description": "Rug decor elements"}', ARRAY['interior']),
('Bookshelves', 'Decor', '{"type": "text", "description": "Bookshelf decor elements"}', ARRAY['interior']),
('Decorative Lighting', 'Decor', '{"type": "text", "description": "Decorative lighting elements"}', ARRAY['interior']),
('Statement Mirrors', 'Decor', '{"type": "text", "description": "Statement mirror decor elements"}', ARRAY['interior']),

-- Environment
('Urban Apartment', 'Environment', '{"type": "text", "description": "Urban apartment environment"}', ARRAY['interior']),
('Rustic Cabin', 'Environment', '{"type": "text", "description": "Rustic cabin environment"}', ARRAY['interior']),
('Beach House', 'Environment', '{"type": "text", "description": "Beach house environment"}', ARRAY['interior']),
('Loft', 'Environment', '{"type": "text", "description": "Loft environment"}', ARRAY['interior']),
('Studio', 'Environment', '{"type": "text", "description": "Studio environment"}', ARRAY['interior']),
('Villa', 'Environment', '{"type": "text", "description": "Villa environment"}', ARRAY['interior']),

-- Budget
('Ultra Budget', 'Budget', '{"type": "text", "description": "Budget range: Under $500"}', ARRAY['interior']),
('Budget Conscious', 'Budget', '{"type": "text", "description": "Budget range: $500 – $1,000"}', ARRAY['interior']),
('Smart Saver', 'Budget', '{"type": "text", "description": "Budget range: $1,000 – $2,000"}', ARRAY['interior']),
('Practical Comfort', 'Budget', '{"type": "text", "description": "Budget range: $2,000 – $5,000"}', ARRAY['interior']),
('Mid-Range', 'Budget', '{"type": "text", "description": "Budget range: $5,000 – $10,000"}', ARRAY['interior']),
('Premium Style', 'Budget', '{"type": "text", "description": "Budget range: $10,000 – $20,000"}', ARRAY['interior']),
('Luxury Living', 'Budget', '{"type": "text", "description": "Budget range: $20,000 – $50,000"}', ARRAY['interior']),
('Unlimited Budget', 'Budget', '{"type": "text", "description": "Budget range: $50,000+"}', ARRAY['interior']),

-- Furniture Styles
('Modern', 'Furniture Style', '{"type": "text", "description": "Clean lines, minimalism, neutral tones"}', ARRAY['interior']),
('Contemporary', 'Furniture Style', '{"type": "text", "description": "Current trends, fluid style"}', ARRAY['interior']),
('Mid-Century Modern', 'Furniture Style', '{"type": "text", "description": "Sleek, retro 1950s–60s vibes"}', ARRAY['interior']),
('Scandinavian', 'Furniture Style', '{"type": "text", "description": "Light woods, soft textures, cozy minimalism"}', ARRAY['interior']),
('Industrial', 'Furniture Style', '{"type": "text", "description": "Raw materials, metal + wood combo"}', ARRAY['interior']),
('Bohemian', 'Furniture Style', '{"type": "text", "description": "Colorful, eclectic, layered patterns"}', ARRAY['interior']),
('Rustic', 'Furniture Style', '{"type": "text", "description": "Reclaimed wood, earthy textures"}', ARRAY['interior']),
('Traditional', 'Furniture Style', '{"type": "text", "description": "Classic furniture, rich woods, elegant decor"}', ARRAY['interior']),
('Farmhouse', 'Furniture Style', '{"type": "text", "description": "Cozy, whitewashed, vintage-inspired"}', ARRAY['interior']),
('Minimalist', 'Furniture Style', '{"type": "text", "description": "Stripped-down, ultra-clean, less is more"}', ARRAY['interior']),
('Transitional', 'Furniture Style', '{"type": "text", "description": "Mix of traditional and modern"}', ARRAY['interior']),
('Art Deco', 'Furniture Style', '{"type": "text", "description": "Geometric patterns, metallics, luxe materials"}', ARRAY['interior']),
('Coastal', 'Furniture Style', '{"type": "text", "description": "Soft blues, sandy neutrals, breezy feel"}', ARRAY['interior']),
('Japanese Zen', 'Furniture Style', '{"type": "text", "description": "Simplicity, natural materials, harmony"}', ARRAY['interior']),
('Victorian', 'Furniture Style', '{"type": "text", "description": "Ornate, antique-inspired"}', ARRAY['interior']),
('Hollywood Regency', 'Furniture Style', '{"type": "text", "description": "Glam, high-contrast, luxurious"}', ARRAY['interior']),
('Urban Modern', 'Furniture Style', '{"type": "text", "description": "Upscale city loft vibes"}', ARRAY['interior']),
('Shabby Chic', 'Furniture Style', '{"type": "text", "description": "Distressed finishes, feminine vintage"}', ARRAY['interior']),
('Eclectic', 'Furniture Style', '{"type": "text", "description": "Bold mix of different styles"}', ARRAY['interior']),
('Wabi-Sabi', 'Furniture Style', '{"type": "text", "description": "Imperfect beauty, organic forms"}', ARRAY['interior']),

-- Outdoor Furniture
('Rattan Patio Set', 'Outdoor Furniture', '{"type": "text", "description": "Classic rattan outdoor seating set"}', ARRAY['interior']),
('Bistro Set', 'Outdoor Furniture', '{"type": "text", "description": "Small outdoor dining set for two"}', ARRAY['interior']),
('Reclining Lounger', 'Outdoor Furniture', '{"type": "text", "description": "Adjustable outdoor lounge chair"}', ARRAY['interior']),
('Hanging Egg Chair', 'Outdoor Furniture', '{"type": "text", "description": "Suspended egg-shaped outdoor chair"}', ARRAY['interior']),
('Gas Fire Table', 'Outdoor Furniture', '{"type": "text", "description": "Outdoor table with built-in gas fire pit"}', ARRAY['interior']),
('Wood Burning Pit', 'Outdoor Furniture', '{"type": "text", "description": "Traditional wood-burning fire pit"}', ARRAY['interior']),
('Cantilever Umbrella', 'Outdoor Furniture', '{"type": "text", "description": "Offset outdoor umbrella with weighted base"}', ARRAY['interior']),
('Table Umbrella', 'Outdoor Furniture', '{"type": "text", "description": "Standard outdoor table umbrella"}', ARRAY['interior']),

-- Office
('Standing Desk', 'Office', '{"type": "text", "description": "Height-adjustable standing desk"}', ARRAY['interior']),
('L-shaped Desk', 'Office', '{"type": "text", "description": "Corner L-shaped workstation desk"}', ARRAY['interior']),
('Minimalist Desk', 'Office', '{"type": "text", "description": "Clean, simple desk design"}', ARRAY['interior']),
('Ergonomic Chair', 'Office', '{"type": "text", "description": "Supportive ergonomic office chair"}', ARRAY['interior']),
('Mesh Back Chair', 'Office', '{"type": "text", "description": "Breathable mesh back office chair"}', ARRAY['interior']),
('Wall-Mounted Shelves', 'Office', '{"type": "text", "description": "Space-saving wall-mounted storage"}', ARRAY['interior']),
('Freestanding Units', 'Office', '{"type": "text", "description": "Modular freestanding storage units"}', ARRAY['interior']),
('Filing Cabinets', 'Office', '{"type": "text", "description": "Document storage filing cabinets"}', ARRAY['interior']),
('Drawer Towers', 'Office', '{"type": "text", "description": "Multi-drawer storage tower"}', ARRAY['interior']),

-- Dining Room
('Round Dining Table', 'Dining Room', '{"type": "text", "description": "Classic round dining table"}', ARRAY['interior']),
('Extendable Table', 'Dining Room', '{"type": "text", "description": "Expandable dining table for flexible seating"}', ARRAY['interior']),
('Farmhouse Table', 'Dining Room', '{"type": "text", "description": "Rustic farmhouse-style dining table"}', ARRAY['interior']),
('Upholstered Chair', 'Dining Room', '{"type": "text", "description": "Comfortable padded dining chair"}', ARRAY['interior']),
('Modern Plastic Chair', 'Dining Room', '{"type": "text", "description": "Contemporary plastic dining chair"}', ARRAY['interior']),
('Mid-century Buffet', 'Dining Room', '{"type": "text", "description": "1950s-inspired dining room storage"}', ARRAY['interior']),
('Rustic Sideboard', 'Dining Room', '{"type": "text", "description": "Country-style dining room storage"}', ARRAY['interior']),
('Chandelier', 'Dining Room', '{"type": "text", "description": "Elegant overhead lighting fixture"}', ARRAY['interior']),
('Pendant Lights', 'Dining Room', '{"type": "text", "description": "Modern hanging light fixtures"}', ARRAY['interior']),

-- Kitchen
('Shaker Cabinets', 'Kitchen', '{"type": "text", "description": "Classic shaker-style kitchen cabinets"}', ARRAY['interior']),
('Flat Panel Cabinets', 'Kitchen', '{"type": "text", "description": "Modern flat-panel kitchen cabinets"}', ARRAY['interior']),
('Rolling Kitchen Island', 'Kitchen', '{"type": "text", "description": "Mobile kitchen island with storage"}', ARRAY['interior']),
('Fixed Butcher Block Island', 'Kitchen', '{"type": "text", "description": "Stationary butcher block kitchen island"}', ARRAY['interior']),
('Subway Tile', 'Kitchen', '{"type": "text", "description": "Classic rectangular kitchen backsplash tile"}', ARRAY['interior']),
('Mosaic Tile', 'Kitchen', '{"type": "text", "description": "Decorative patterned kitchen backsplash tile"}', ARRAY['interior']),
('Swivel Stool', 'Kitchen', '{"type": "text", "description": "Rotating kitchen counter stool"}', ARRAY['interior']),
('Industrial Stool', 'Kitchen', '{"type": "text", "description": "Metal-framed industrial-style kitchen stool"}', ARRAY['interior']),

-- Bedroom
('Twin Bed', 'Bedroom', '{"type": "text", "description": "Single twin-sized bed"}', ARRAY['interior']),
('Queen Bed', 'Bedroom', '{"type": "text", "description": "Standard queen-sized bed"}', ARRAY['interior']),
('King Platform Bed', 'Bedroom', '{"type": "text", "description": "Modern king-sized platform bed"}', ARRAY['interior']),
('Bunk Bed', 'Bedroom', '{"type": "text", "description": "Stacked twin beds with ladder"}', ARRAY['interior']),
('Floating Nightstand', 'Bedroom', '{"type": "text", "description": "Wall-mounted bedside table"}', ARRAY['interior']),
('Two-Drawer Nightstand', 'Bedroom', '{"type": "text", "description": "Traditional bedside table with drawers"}', ARRAY['interior']),
('6-Drawer Dresser', 'Bedroom', '{"type": "text", "description": "Wide dresser with six drawers"}', ARRAY['interior']),
('Tallboy Dresser', 'Bedroom', '{"type": "text", "description": "Tall narrow dresser with multiple drawers"}', ARRAY['interior']),
('Upholstered Headboard', 'Bedroom', '{"type": "text", "description": "Padded fabric headboard"}', ARRAY['interior']),
('Wood Panel Headboard', 'Bedroom', '{"type": "text", "description": "Solid wood panel headboard"}', ARRAY['interior']),

-- Living Room
('Sectional Sofa', 'Living Room', '{"type": "text", "description": "Modular L-shaped or U-shaped sofa"}', ARRAY['interior']),
('Loveseat', 'Living Room', '{"type": "text", "description": "Two-seater sofa"}', ARRAY['interior']),
('Recliner Sofa', 'Living Room', '{"type": "text", "description": "Adjustable reclining sofa"}', ARRAY['interior']),
('Sleeper Sofa', 'Living Room', '{"type": "text", "description": "Convertible sofa bed"}', ARRAY['interior']),
('Glass Coffee Table', 'Living Room', '{"type": "text", "description": "Modern glass-top coffee table"}', ARRAY['interior']),
('Lift-Top Coffee Table', 'Living Room', '{"type": "text", "description": "Convertible coffee table with lift mechanism"}', ARRAY['interior']),
('Round Wood Coffee Table', 'Living Room', '{"type": "text", "description": "Classic wooden round coffee table"}', ARRAY['interior']),
('Minimalist Stand', 'Living Room', '{"type": "text", "description": "Simple TV stand"}', ARRAY['interior']),
('Entertainment Center', 'Living Room', '{"type": "text", "description": "Comprehensive media storage unit"}', ARRAY['interior']),
('Floating TV Console', 'Living Room', '{"type": "text", "description": "Wall-mounted TV stand"}', ARRAY['interior']),
('Wingback Chair', 'Living Room', '{"type": "text", "description": "Classic high-back armchair"}', ARRAY['interior']),
('Slipper Chair', 'Living Room', '{"type": "text", "description": "Armless upholstered chair"}', ARRAY['interior']),
('Swivel Chair', 'Living Room', '{"type": "text", "description": "Rotating lounge chair"}', ARRAY['interior']),
('Ladder Shelf', 'Living Room', '{"type": "text", "description": "Leaning bookshelf with ladder design"}', ARRAY['interior']),
('Modular Bookshelf', 'Living Room', '{"type": "text", "description": "Customizable bookshelf system"}', ARRAY['interior']),
('Industrial Bookshelf', 'Living Room', '{"type": "text", "description": "Metal-framed industrial-style bookshelf"}', ARRAY['interior']),

-- Emotions (Logo Mode)
('Joyful', 'Emotions', '{"type": "text", "description": "Bright, uplifting, and cheerful design elements"}', ARRAY['logo']),
('Elegant', 'Emotions', '{"type": "text", "description": "Sophisticated, refined, and graceful design elements"}', ARRAY['logo']),
('Powerful', 'Emotions', '{"type": "text", "description": "Strong, bold, and commanding design elements"}', ARRAY['logo']),
('Trustworthy', 'Emotions', '{"type": "text", "description": "Reliable, stable, and secure design elements"}', ARRAY['logo']),
('Innovative', 'Emotions', '{"type": "text", "description": "Creative, forward-thinking, and modern design elements"}', ARRAY['logo']),
('Friendly', 'Emotions', '{"type": "text", "description": "Warm, approachable, and welcoming design elements"}', ARRAY['logo']),
('Luxurious', 'Emotions', '{"type": "text", "description": "Premium, exclusive, and high-end design elements"}', ARRAY['logo']),
('Playful', 'Emotions', '{"type": "text", "description": "Fun, energetic, and whimsical design elements"}', ARRAY['logo']),
('Professional', 'Emotions', '{"type": "text", "description": "Competent, reliable, and business-oriented design elements"}', ARRAY['logo']),
('Calm', 'Emotions', '{"type": "text", "description": "Peaceful, serene, and balanced design elements"}', ARRAY['logo']),
('Dynamic', 'Emotions', '{"type": "text", "description": "Energetic, active, and movement-oriented design elements"}', ARRAY['logo']),
('Minimalist', 'Emotions', '{"type": "text", "description": "Clean, simple, and essential design elements"}', ARRAY['logo']),
('Bold', 'Emotions', '{"type": "text", "description": "Strong, confident, and impactful design elements"}', ARRAY['logo']),
('Eco-Friendly', 'Emotions', '{"type": "text", "description": "Natural, sustainable, and environmentally conscious design elements"}', ARRAY['logo']),
('Tech-Savvy', 'Emotions', '{"type": "text", "description": "Modern, digital, and innovative design elements"}', ARRAY['logo']),
('Traditional', 'Emotions', '{"type": "text", "description": "Classic, timeless, and heritage-inspired design elements"}', ARRAY['logo']),
('Youthful', 'Emotions', '{"type": "text", "description": "Fresh, vibrant, and contemporary design elements"}', ARRAY['logo']),
('Sophisticated', 'Emotions', '{"type": "text", "description": "Elegant, refined, and cultured design elements"}', ARRAY['logo']),
('Adventurous', 'Emotions', '{"type": "text", "description": "Bold, daring, and exploratory design elements"}', ARRAY['logo']),
('Reliable', 'Emotions', '{"type": "text", "description": "Dependable, consistent, and trustworthy design elements"}', ARRAY['logo']),

-- Logo Vibe
('Bold & Powerful', 'Logo Vibe', '{"type": "text", "description": "Strong, impactful, and commanding design elements"}', ARRAY['logo']),
('Minimalist & Clean', 'Logo Vibe', '{"type": "text", "description": "Simple, essential, and uncluttered design elements"}', ARRAY['logo']),
('Modern & Innovative', 'Logo Vibe', '{"type": "text", "description": "Contemporary, forward-thinking, and cutting-edge design elements"}', ARRAY['logo']),
('Playful & Fun', 'Logo Vibe', '{"type": "text", "description": "Lighthearted, energetic, and entertaining design elements"}', ARRAY['logo']),
('Elegant & Luxurious', 'Logo Vibe', '{"type": "text", "description": "Sophisticated, premium, and high-end design elements"}', ARRAY['logo']),
('Trustworthy & Reliable', 'Logo Vibe', '{"type": "text", "description": "Dependable, stable, and secure design elements"}', ARRAY['logo']),
('Techy & Futuristic', 'Logo Vibe', '{"type": "text", "description": "Digital, advanced, and forward-looking design elements"}', ARRAY['logo']),
('Friendly & Approachable', 'Logo Vibe', '{"type": "text", "description": "Warm, welcoming, and accessible design elements"}', ARRAY['logo']),
('Serious & Professional', 'Logo Vibe', '{"type": "text", "description": "Competent, business-oriented, and formal design elements"}', ARRAY['logo']),
('Creative & Artistic', 'Logo Vibe', '{"type": "text", "description": "Imaginative, expressive, and unique design elements"}', ARRAY['logo']),
('Youthful & Energetic', 'Logo Vibe', '{"type": "text", "description": "Fresh, vibrant, and dynamic design elements"}', ARRAY['logo']),
('Vintage & Nostalgic', 'Logo Vibe', '{"type": "text", "description": "Retro, classic, and timeless design elements"}', ARRAY['logo']),
('High-End & Exclusive', 'Logo Vibe', '{"type": "text", "description": "Premium, elite, and luxury design elements"}', ARRAY['logo']),
('Organic & Natural', 'Logo Vibe', '{"type": "text", "description": "Earthy, flowing, and nature-inspired design elements"}', ARRAY['logo']),
('Edgy & Disruptive', 'Logo Vibe', '{"type": "text", "description": "Bold, unconventional, and boundary-pushing design elements"}', ARRAY['logo']),
('Quirky & Unique', 'Logo Vibe', '{"type": "text", "description": "Unusual, distinctive, and memorable design elements"}', ARRAY['logo']),
('Spiritual & Calming', 'Logo Vibe', '{"type": "text", "description": "Peaceful, meditative, and balanced design elements"}', ARRAY['logo']),
('Bold & Geometric', 'Logo Vibe', '{"type": "text", "description": "Strong, structured, and angular design elements"}', ARRAY['logo']),
('Corporate & Formal', 'Logo Vibe', '{"type": "text", "description": "Professional, traditional, and business-oriented design elements"}', ARRAY['logo']),
('Human-Centered & Empathetic', 'Logo Vibe', '{"type": "text", "description": "Compassionate, understanding, and people-focused design elements"}', ARRAY['logo']),
('Eco-Friendly & Sustainable', 'Logo Vibe', '{"type": "text", "description": "Green, environmentally conscious, and natural design elements"}', ARRAY['logo']),
('Abstract & Conceptual', 'Logo Vibe', '{"type": "text", "description": "Non-representational, symbolic, and thought-provoking design elements"}', ARRAY['logo']),
('Dynamic & Motion-Inspired', 'Logo Vibe', '{"type": "text", "description": "Energetic, flowing, and movement-based design elements"}', ARRAY['logo']),
('Luxury Minimalism', 'Logo Vibe', '{"type": "text", "description": "Refined, essential, and premium design elements"}', ARRAY['logo']),
('Urban & Street Style', 'Logo Vibe', '{"type": "text", "description": "Contemporary, edgy, and city-inspired design elements"}', ARRAY['logo']),
('Cute & Whimsical', 'Logo Vibe', '{"type": "text", "description": "Playful, charming, and delightful design elements"}', ARRAY['logo']),
('Confident & Assertive', 'Logo Vibe', '{"type": "text", "description": "Strong, decisive, and impactful design elements"}', ARRAY['logo']),
('Warm & Welcoming', 'Logo Vibe', '{"type": "text", "description": "Inviting, friendly, and comforting design elements"}', ARRAY['logo']),
('Sophisticated & Refined', 'Logo Vibe', '{"type": "text", "description": "Elegant, cultured, and polished design elements"}', ARRAY['logo']),
('Mysterious & Dark', 'Logo Vibe', '{"type": "text", "description": "Intriguing, enigmatic, and dramatic design elements"}', ARRAY['logo']),

-- Industry
('Technology', 'Industry', '{"type": "text", "description": "Tech-focused design elements for software, hardware, and digital services"}', ARRAY['logo']),
('Healthcare', 'Industry', '{"type": "text", "description": "Medical and wellness-focused design elements"}', ARRAY['logo']),
('Finance', 'Industry', '{"type": "text", "description": "Financial services and banking design elements"}', ARRAY['logo']),
('Education', 'Industry', '{"type": "text", "description": "Educational institution and learning-focused design elements"}', ARRAY['logo']),
('Retail', 'Industry', '{"type": "text", "description": "Retail and shopping-focused design elements"}', ARRAY['logo']),
('Real Estate', 'Industry', '{"type": "text", "description": "Property and real estate-focused design elements"}', ARRAY['logo']),
('Food & Beverage', 'Industry', '{"type": "text", "description": "Culinary and hospitality-focused design elements"}', ARRAY['logo']),
('Fashion & Apparel', 'Industry', '{"type": "text", "description": "Clothing and fashion-focused design elements"}', ARRAY['logo']),
('Beauty & Wellness', 'Industry', '{"type": "text", "description": "Beauty, spa, and wellness-focused design elements"}', ARRAY['logo']),
('Media & Entertainment', 'Industry', '{"type": "text", "description": "Entertainment and media-focused design elements"}', ARRAY['logo']),
('Travel & Tourism', 'Industry', '{"type": "text", "description": "Travel and tourism-focused design elements"}', ARRAY['logo']),
('Fitness & Sports', 'Industry', '{"type": "text", "description": "Sports and fitness-focused design elements"}', ARRAY['logo']),
('Transportation & Logistics', 'Industry', '{"type": "text", "description": "Transport and logistics-focused design elements"}', ARRAY['logo']),
('Automotive', 'Industry', '{"type": "text", "description": "Automobile and vehicle-focused design elements"}', ARRAY['logo']),
('Legal Services', 'Industry', '{"type": "text", "description": "Legal and law-focused design elements"}', ARRAY['logo']),
('Construction & Architecture', 'Industry', '{"type": "text", "description": "Building and architectural design elements"}', ARRAY['logo']),
('Agriculture', 'Industry', '{"type": "text", "description": "Farming and agricultural-focused design elements"}', ARRAY['logo']),
('Energy & Utilities', 'Industry', '{"type": "text", "description": "Energy and utility-focused design elements"}', ARRAY['logo']),
('Government & Public Sector', 'Industry', '{"type": "text", "description": "Government and public service-focused design elements"}', ARRAY['logo']),
('Non-Profit / Charity', 'Industry', '{"type": "text", "description": "Charitable and non-profit organization design elements"}', ARRAY['logo']),
('Marketing & Advertising', 'Industry', '{"type": "text", "description": "Marketing and advertising-focused design elements"}', ARRAY['logo']),
('HR & Recruiting', 'Industry', '{"type": "text", "description": "Human resources and recruitment-focused design elements"}', ARRAY['logo']),
('Event Planning', 'Industry', '{"type": "text", "description": "Event and celebration-focused design elements"}', ARRAY['logo']),
('Home Services', 'Industry', '{"type": "text", "description": "Home maintenance and service-focused design elements"}', ARRAY['logo']),
('Pet Care', 'Industry', '{"type": "text", "description": "Pet and animal care-focused design elements"}', ARRAY['logo']),
('Gaming & Esports', 'Industry', '{"type": "text", "description": "Gaming and esports-focused design elements"}', ARRAY['logo']),
('Art & Design', 'Industry', '{"type": "text", "description": "Artistic and design-focused design elements"}', ARRAY['logo']),
('Spiritual / Religious', 'Industry', '{"type": "text", "description": "Spiritual and religious-focused design elements"}', ARRAY['logo']),
('Startups / Entrepreneurs', 'Industry', '{"type": "text", "description": "Startup and entrepreneurial-focused design elements"}', ARRAY['logo']),
('Luxury & Lifestyle', 'Industry', '{"type": "text", "description": "Luxury and lifestyle-focused design elements"}', ARRAY['logo']),

-- Logo Shape
('Circle', 'Logo Shape', '{"type": "text", "description": "Balanced, unified, and inclusive circular design"}', ARRAY['logo']),
('Square / Boxy', 'Logo Shape', '{"type": "text", "description": "Stable, solid, and trustworthy square design"}', ARRAY['logo']),
('Vertical Rectangle', 'Logo Shape', '{"type": "text", "description": "Modern and strong badge or monolith design"}', ARRAY['logo']),
('Horizontal Rectangle', 'Logo Shape', '{"type": "text", "description": "Wide, banner-like, and professional design"}', ARRAY['logo']),
('Triangle / Pointed', 'Logo Shape', '{"type": "text", "description": "Dynamic, edgy, and innovative triangular design"}', ARRAY['logo']),
('Hexagon', 'Logo Shape', '{"type": "text", "description": "Futuristic, geometric, and tech-savvy hexagonal design"}', ARRAY['logo']),
('Diamond / Rhombus', 'Logo Shape', '{"type": "text", "description": "Sophisticated, sharp, and unique diamond design"}', ARRAY['logo']),
('Star', 'Logo Shape', '{"type": "text", "description": "Energetic, eye-catching, and iconic star design"}', ARRAY['logo']),
('Badge / Emblem', 'Logo Shape', '{"type": "text", "description": "Vintage-style crest, perfect for traditional or artisan brands"}', ARRAY['logo']),
('Pill / Capsule', 'Logo Shape', '{"type": "text", "description": "Friendly and modern pill-shaped design"}', ARRAY['logo']),
('Wavy / Irregular Shape', 'Logo Shape', '{"type": "text", "description": "Artistic and unconventional flowing design"}', ARRAY['logo']),
('Geometric Cluster', 'Logo Shape', '{"type": "text", "description": "Complex visual formed by combined geometric shapes"}', ARRAY['logo']),
('Stacked Text & Icon', 'Logo Shape', '{"type": "text", "description": "Icon positioned above text in a vertical arrangement"}', ARRAY['logo']),
('Side-by-Side Icon & Text', 'Logo Shape', '{"type": "text", "description": "Clean and standard horizontal arrangement of icon and text"}', ARRAY['logo']),
('Integrated Icon/Text', 'Logo Shape', '{"type": "text", "description": "Text creatively woven into the icon or shape"}', ARRAY['logo']),
('Framed Logo', 'Logo Shape', '{"type": "text", "description": "Logo enclosed within a decorative frame or border"}', ARRAY['logo']),
('Floating Icon', 'Logo Shape', '{"type": "text", "description": "Symbol subtly hovering or overlaying the design"}', ARRAY['logo']),
('Negative Space', 'Logo Shape', '{"type": "text", "description": "Designs formed using strategic gaps and spaces"}', ARRAY['logo']),
('Radial Symmetry', 'Logo Shape', '{"type": "text", "description": "Symmetrical design radiating from the center"}', ARRAY['logo']),
('Asymmetrical / Freeform', 'Logo Shape', '{"type": "text", "description": "Creative and flowing design without rigid structure"}', ARRAY['logo']),

-- Logo Style
('Modern', 'Logo Style', '{"type": "text", "description": "Sleek, minimal, and contemporary design approach"}', ARRAY['logo']),
('Classic', 'Logo Style', '{"type": "text", "description": "Traditional and timeless design elements"}', ARRAY['logo']),
('Vintage', 'Logo Style', '{"type": "text", "description": "Retro and old-school charm design elements"}', ARRAY['logo']),
('Minimalist', 'Logo Style', '{"type": "text", "description": "Simple, clean lines with strategic white space"}', ARRAY['logo']),
('Bold', 'Logo Style', '{"type": "text", "description": "Strong shapes and thick, impactful typography"}', ARRAY['logo']),
('Elegant', 'Logo Style', '{"type": "text", "description": "Classy and refined design elements"}', ARRAY['logo']),
('Playful', 'Logo Style', '{"type": "text", "description": "Fun, colorful, and lighthearted design approach"}', ARRAY['logo']),
('Professional', 'Logo Style', '{"type": "text", "description": "Trustworthy and corporate design elements"}', ARRAY['logo']),
('Creative', 'Logo Style', '{"type": "text", "description": "Artsy and experimental design approach"}', ARRAY['logo']),
('Techy', 'Logo Style', '{"type": "text", "description": "Futuristic and digital design elements"}', ARRAY['logo']),
('Eco-Friendly', 'Logo Style', '{"type": "text", "description": "Natural and sustainable design elements"}', ARRAY['logo']),
('Luxury', 'Logo Style', '{"type": "text", "description": "High-end and premium design elements"}', ARRAY['logo']),
('Industrial', 'Logo Style', '{"type": "text", "description": "Rugged and raw material-inspired design"}', ARRAY['logo']),
('Handmade', 'Logo Style', '{"type": "text", "description": "Crafty, imperfect, and authentic design elements"}', ARRAY['logo']),
('Geometric', 'Logo Style', '{"type": "text", "description": "Sharp lines and structured shapes"}', ARRAY['logo']),
('Organic', 'Logo Style', '{"type": "text", "description": "Flowing and natural form-inspired design"}', ARRAY['logo']),
('Abstract', 'Logo Style', '{"type": "text", "description": "Conceptual and symbolic design elements"}', ARRAY['logo']),
('Monogram', 'Logo Style', '{"type": "text", "description": "Initials-based design approach"}', ARRAY['logo']),
('Wordmark', 'Logo Style', '{"type": "text", "description": "Text-only design approach"}', ARRAY['logo']),
('Emblem', 'Logo Style', '{"type": "text", "description": "Icon and text combined within a shape"}', ARRAY['logo']),
('Gradient', 'Logo Style', '{"type": "text", "description": "Color blending and fading effects"}', ARRAY['logo']),
('3D / Isometric', 'Logo Style', '{"type": "text", "description": "Depth and perspective-based design"}', ARRAY['logo']),
('Flat', 'Logo Style', '{"type": "text", "description": "Clean colors without shadows or depth"}', ARRAY['logo']),
('Animated / Motion-Inspired', 'Logo Style', '{"type": "text", "description": "Dynamic and movement-suggesting design"}', ARRAY['logo']),
('Black & White', 'Logo Style', '{"type": "text", "description": "High contrast, timeless monochrome design"}', ARRAY['logo']),
('Colorful', 'Logo Style', '{"type": "text", "description": "Bold and vibrant color usage"}', ARRAY['logo']),
('Luxury Script', 'Logo Style', '{"type": "text", "description": "Flowing calligraphy and elegant typography"}', ARRAY['logo']),
('Tech Minimal', 'Logo Style', '{"type": "text", "description": "Streamlined and software-oriented design"}', ARRAY['logo']),
('Friendly / Rounded', 'Logo Style', '{"type": "text", "description": "Soft corners and bubbly shapes"}', ARRAY['logo']),
('Edgy / Sharp', 'Logo Style', '{"type": "text", "description": "Aggressive and bold design elements"}', ARRAY['logo']),

-- Marketing Perspective
('Centered Framing', 'Marketing Perspective', '{"type": "text", "description": "Product placed dead center for maximum focus"}', ARRAY['marketing']),
('Rule of Thirds', 'Marketing Perspective', '{"type": "text", "description": "Classic off-center composition for visual balance"}', ARRAY['marketing']),
('Symmetrical Composition', 'Marketing Perspective', '{"type": "text", "description": "Mirrored left/right arrangement for harmony"}', ARRAY['marketing']),
('Minimalist Cropping', 'Marketing Perspective', '{"type": "text", "description": "Strategic partial product view for intrigue"}', ARRAY['marketing']),
('Tight Crop / Close-Up', 'Marketing Perspective', '{"type": "text", "description": "Detailed focus on specific product features"}', ARRAY['marketing']),
('Top-Down (Flat Lay)', 'Marketing Perspective', '{"type": "text", "description": "Direct overhead view for comprehensive display"}', ARRAY['marketing']),
('45° Angle', 'Marketing Perspective', '{"type": "text", "description": "Popular product angle showing depth and dimension"}', ARRAY['marketing']),
('Eye-Level', 'Marketing Perspective', '{"type": "text", "description": "Natural, human perspective for realism"}', ARRAY['marketing']),
('Worm\'s Eye View', 'Marketing Perspective', '{"type": "text", "description": "Dramatic upward perspective for impact"}', ARRAY['marketing']),
('Bird\'s Eye View', 'Marketing Perspective', '{"type": "text", "description": "Wide overhead scene perspective"}', ARRAY['marketing']),
('Shallow Depth of Field', 'Marketing Perspective', '{"type": "text", "description": "Blurred background with sharp subject focus"}', ARRAY['marketing']),
('Full Focus', 'Marketing Perspective', '{"type": "text", "description": "Everything in sharp, clear detail"}', ARRAY['marketing']),
('Foreground Blur', 'Marketing Perspective', '{"type": "text", "description": "Looking through elements for depth"}', ARRAY['marketing']),
('Motion Blur', 'Marketing Perspective', '{"type": "text", "description": "Dynamic movement and energy effect"}', ARRAY['marketing']),
('Focus Pull', 'Marketing Perspective', '{"type": "text", "description": "Sharp subject with storytelling background"}', ARRAY['marketing']),
('Dutch Angle (Tilted)', 'Marketing Perspective', '{"type": "text", "description": "Dramatic tilted perspective"}', ARRAY['marketing']),
('Negative Space', 'Marketing Perspective', '{"type": "text", "description": "Minimal elements with strategic text space"}', ARRAY['marketing']),
('Framed Subject', 'Marketing Perspective', '{"type": "text", "description": "Product viewed through contextual framing"}', ARRAY['marketing']),
('Low-Key Lighting', 'Marketing Perspective', '{"type": "text", "description": "Dark, moody atmosphere with dramatic shadows"}', ARRAY['marketing']),
('High-Key Lighting', 'Marketing Perspective', '{"type": "text", "description": "Bright, even illumination for clarity"}', ARRAY['marketing']),
('Floating Object', 'Marketing Perspective', '{"type": "text", "description": "Product suspended in mid-air for emphasis"}', ARRAY['marketing']),
('Exploded View', 'Marketing Perspective', '{"type": "text", "description": "Product parts separated for detailed display"}', ARRAY['marketing']),
('360° Style View', 'Marketing Perspective', '{"type": "text", "description": "Dynamic rotating product presentation"}', ARRAY['marketing']),
('Scale Context', 'Marketing Perspective', '{"type": "text", "description": "Product shown with everyday items for size reference"}', ARRAY['marketing']),
('Hero Shot', 'Marketing Perspective', '{"type": "text", "description": "Glamorous, dramatic centerstage presentation"}', ARRAY['marketing']),
('Hand-Held Feel', 'Marketing Perspective', '{"type": "text", "description": "Slightly unsteady, personal perspective"}', ARRAY['marketing']),
('Over-the-Shoulder', 'Marketing Perspective', '{"type": "text", "description": "Person using the product in context"}', ARRAY['marketing']),
('POV (Point of View)', 'Marketing Perspective', '{"type": "text", "description": "User\'s perspective of product interaction"}', ARRAY['marketing']),
('In-Use Action Shot', 'Marketing Perspective', '{"type": "text", "description": "Product in mid-gesture or interaction"}', ARRAY['marketing']),
('Flat Product Card View', 'Marketing Perspective', '{"type": "text", "description": "E-commerce style product on white background"}', ARRAY['marketing']),

-- Tattoo Style presets
INSERT INTO presets (name, category, content, modes) VALUES
('Traditional (American Old School)', 'Tattoo Style', '{"type": "Text", "description": "Classic American tattoo style featuring bold outlines, limited color palette, and iconic imagery like roses, daggers, and eagles."}', ARRAY['tattoo']),
('Neo-Traditional', 'Tattoo Style', '{"type": "Text", "description": "Modern take on traditional tattoos with more depth, detail, and a wider color palette while maintaining bold outlines."}', ARRAY['tattoo']),
('Fine Line', 'Tattoo Style', '{"type": "Text", "description": "Delicate, thin line work creating detailed and intricate designs, often with minimal shading."}', ARRAY['tattoo']),
('Blackwork', 'Tattoo Style', '{"type": "Text", "description": "Tattoos created using only black ink, ranging from solid black areas to intricate patterns and designs."}', ARRAY['tattoo']),
('Watercolor', 'Tattoo Style', '{"type": "Text", "description": "Tattoo style mimicking watercolor paintings with soft edges, color blending, and painterly effects."}', ARRAY['tattoo']),
('Geometric', 'Tattoo Style', '{"type": "Text", "description": "Tattoos featuring precise geometric shapes, patterns, and symmetry, often incorporating sacred geometry."}', ARRAY['tattoo']),
('Realism', 'Tattoo Style', '{"type": "Text", "description": "Photorealistic tattoos that aim to replicate the appearance of real objects, portraits, or scenes."}', ARRAY['tattoo']),
('Japanese Irezumi', 'Tattoo Style', '{"type": "Text", "description": "Traditional Japanese tattoo style featuring mythological creatures, waves, flowers, and other traditional motifs."}', ARRAY['tattoo']),
('Tribal', 'Tattoo Style', '{"type": "Text", "description": "Bold black patterns inspired by indigenous art from various cultures, often featuring intricate line work."}', ARRAY['tattoo']),
('Minimalist', 'Tattoo Style', '{"type": "Text", "description": "Simple, clean designs with minimal detail, often using thin lines and negative space."}', ARRAY['tattoo']),
('Trash Polka', 'Tattoo Style', '{"type": "Text", "description": "Contemporary style combining realistic elements with abstract splashes of red and black."}', ARRAY['tattoo']),
('Dotwork', 'Tattoo Style', '{"type": "Text", "description": "Tattoos created using only dots, creating shading and patterns through stippling techniques."}', ARRAY['tattoo']),
('Illustrative', 'Tattoo Style', '{"type": "Text", "description": "Style that combines elements of traditional and modern art, often with a hand-drawn or sketch-like quality."}', ARRAY['tattoo']),
('Abstract', 'Tattoo Style', '{"type": "Text", "description": "Non-representational designs that focus on shapes, colors, and forms rather than realistic imagery."}', ARRAY['tattoo']),
('Biomechanical', 'Tattoo Style', '{"type": "Text", "description": "Style that combines mechanical elements with organic forms, creating the illusion of machinery beneath the skin."}', ARRAY['tattoo']),

-- Tattoo Theme presets
INSERT INTO presets (name, category, content, modes) VALUES
('Animal / Wildlife', 'Tattoo Theme', '{"type": "Text", "description": "Representations of animals and wildlife, from realistic portraits to stylized interpretations of creatures."}', ARRAY['tattoo']),
('Spiritual / Sacred Geometry', 'Tattoo Theme', '{"type": "Text", "description": "Geometric patterns and symbols with spiritual significance, often incorporating mandalas and sacred shapes."}', ARRAY['tattoo']),
('Floral / Botanical', 'Tattoo Theme', '{"type": "Text", "description": "Plant-based designs including flowers, leaves, and botanical elements, from delicate to bold styles."}', ARRAY['tattoo']),
('Mythology / Gods', 'Tattoo Theme', '{"type": "Text", "description": "Deities, mythological creatures, and stories from various cultural traditions and legends."}', ARRAY['tattoo']),
('Skulls & Bones', 'Tattoo Theme', '{"type": "Text", "description": "Skeletal imagery ranging from traditional skull designs to anatomical illustrations."}', ARRAY['tattoo']),
('Portrait / Face', 'Tattoo Theme', '{"type": "Text", "description": "Realistic or stylized representations of human faces, from loved ones to iconic figures."}', ARRAY['tattoo']),
('Fantasy / Magic', 'Tattoo Theme', '{"type": "Text", "description": "Imaginary creatures, magical elements, and fantastical scenes from myth and fiction."}', ARRAY['tattoo']),
('Ocean / Nautical', 'Tattoo Theme', '{"type": "Text", "description": "Marine life, waves, ships, and other sea-related imagery with traditional or modern interpretations."}', ARRAY['tattoo']),
('Quote / Lettering', 'Tattoo Theme', '{"type": "Text", "description": "Text-based designs including quotes, names, and meaningful words in various typographic styles."}', ARRAY['tattoo']),
('Tech / Circuitry', 'Tattoo Theme', '{"type": "Text", "description": "Technology-inspired designs featuring circuit patterns, digital elements, and futuristic imagery."}', ARRAY['tattoo']),
('Horror / Dark Art', 'Tattoo Theme', '{"type": "Text", "description": "Dark and macabre imagery inspired by horror themes, from subtle to graphic designs."}', ARRAY['tattoo']),
('Abstract Shapes', 'Tattoo Theme', '{"type": "Text", "description": "Non-representational designs focusing on shapes, patterns, and geometric compositions."}', ARRAY['tattoo']),
('Space / Galaxy', 'Tattoo Theme', '{"type": "Text", "description": "Celestial bodies, cosmic scenes, and astronomical elements in realistic or stylized forms."}', ARRAY['tattoo']),
('Nature / Forest', 'Tattoo Theme', '{"type": "Text", "description": "Natural landscapes, trees, and wilderness scenes capturing the beauty of the natural world."}', ARRAY['tattoo']),
('Gothic / Occult', 'Tattoo Theme', '{"type": "Text", "description": "Dark and mysterious imagery inspired by gothic art and occult symbolism."}', ARRAY['tattoo']),

-- Tattoo Vibe presets
INSERT INTO presets (name, category, content, modes) VALUES
('Bold & Graphic', 'Tattoo Vibe', '{"type": "Text", "description": "Strong, impactful designs with clear lines and high contrast, making a powerful visual statement."}', ARRAY['tattoo']),
('Delicate & Subtle', 'Tattoo Vibe', '{"type": "Text", "description": "Fine, gentle designs with soft lines and minimal shading, creating an elegant and understated look."}', ARRAY['tattoo']),
('Whimsical & Playful', 'Tattoo Vibe', '{"type": "Text", "description": "Lighthearted and fun designs with creative elements, often incorporating humor or fantasy themes."}', ARRAY['tattoo']),
('Dark & Mysterious', 'Tattoo Vibe', '{"type": "Text", "description": "Moody and enigmatic designs with deep shadows and occult or gothic elements."}', ARRAY['tattoo']),
('Romantic & Feminine', 'Tattoo Vibe', '{"type": "Text", "description": "Graceful and elegant designs with flowing lines and soft elements, often featuring floral or delicate patterns."}', ARRAY['tattoo']),
('Masculine & Powerful', 'Tattoo Vibe', '{"type": "Text", "description": "Strong, bold designs with heavy lines and traditional elements, conveying strength and authority."}', ARRAY['tattoo']),
('Edgy & Punk', 'Tattoo Vibe', '{"type": "Text", "description": "Rebellious and unconventional designs with raw energy and alternative aesthetics."}', ARRAY['tattoo']),
('Modern & Clean', 'Tattoo Vibe', '{"type": "Text", "description": "Contemporary designs with minimal elements and precise execution, focusing on simplicity and clarity."}', ARRAY['tattoo']),
('Vintage-Inspired', 'Tattoo Vibe', '{"type": "Text", "description": "Classic designs with a nostalgic feel, often incorporating traditional tattoo elements with an aged appearance."}', ARRAY['tattoo']),
('Sacred & Symbolic', 'Tattoo Vibe', '{"type": "Text", "description": "Meaningful designs with spiritual or cultural significance, often incorporating traditional symbols and motifs."}', ARRAY['tattoo']),

-- Headshot Background presets
INSERT INTO presets (name, category, content, modes) VALUES
('Studio White', 'Background', '{"type": "Text", "description": "Clean, professional white studio background for a classic headshot look."}', ARRAY['headshot']),
('Soft Gradient', 'Background', '{"type": "Text", "description": "Smooth, subtle gradient background that adds depth without distraction."}', ARRAY['headshot']),
('Office Environment', 'Background', '{"type": "Text", "description": "Professional office setting background, perfect for corporate headshots."}', ARRAY['headshot']),
('Library / Bookshelves', 'Background', '{"type": "Text", "description": "Elegant bookshelf background that adds sophistication and character."}', ARRAY['headshot']),
('Nature / Trees Blurred', 'Background', '{"type": "Text", "description": "Soft, blurred natural background that adds organic warmth to the portrait."}', ARRAY['headshot']),
('Cityscape Blur', 'Background', '{"type": "Text", "description": "Urban environment with artistic blur, perfect for modern professional portraits."}', ARRAY['headshot']),
('Pastel Color Wash', 'Background', '{"type": "Text", "description": "Soft, muted color background that adds a gentle, artistic touch."}', ARRAY['headshot']),
('Brick Wall', 'Background', '{"type": "Text", "description": "Textured brick background that adds character and urban appeal."}', ARRAY['headshot']),
('Abstract Shapes', 'Background', '{"type": "Text", "description": "Modern abstract pattern background for a contemporary look."}', ARRAY['headshot']),
('Custom Brand Color', 'Background', '{"type": "Text", "description": "Background color matching your brand identity. Enter a HEX color code to customize."}', ARRAY['headshot']),

-- Headshot Lighting presets
INSERT INTO presets (name, category, content, modes) VALUES
('Natural Window Light', 'Lighting', '{"type": "Text", "description": "Soft, diffused natural light from a window, creating a flattering and organic look."}', ARRAY['headshot']),
('Golden Hour Glow', 'Lighting', '{"type": "Text", "description": "Warm, golden sunlight during sunrise or sunset, creating a magical and flattering glow."}', ARRAY['headshot']),
('Softbox Studio', 'Lighting', '{"type": "Text", "description": "Professional studio lighting with soft, even illumination and minimal shadows."}', ARRAY['headshot']),
('Hard Contrast Lighting', 'Lighting', '{"type": "Text", "description": "Dramatic lighting with strong shadows and highlights for a bold, artistic look."}', ARRAY['headshot']),
('Ring Light Front-Facing', 'Lighting', '{"type": "Text", "description": "Even, circular illumination that eliminates shadows and creates a modern, clean look."}', ARRAY['headshot']),
('Backlit Halo Effect', 'Lighting', '{"type": "Text", "description": "Light source behind the subject creating a glowing edge and dramatic silhouette."}', ARRAY['headshot']),
('Neon Edge Glow', 'Lighting', '{"type": "Text", "description": "Colorful neon lighting that creates vibrant edge highlights and modern atmosphere."}', ARRAY['headshot']),
('Moody Shadows', 'Lighting', '{"type": "Text", "description": "Low-key lighting with deep shadows for a dramatic, artistic portrait."}', ARRAY['headshot']),
('Even Fill Light', 'Lighting', '{"type": "Text", "description": "Balanced, shadow-free lighting that evenly illuminates the subject."}', ARRAY['headshot']),
('Vintage Warm Tint', 'Lighting', '{"type": "Text", "description": "Warm, slightly amber-toned lighting reminiscent of classic portrait photography."}', ARRAY['headshot']),

-- Headshot Purpose presets
INSERT INTO presets (name, category, content, modes) VALUES
('LinkedIn Profile Pic', 'Purpose', '{"type": "Text", "description": "Professional, approachable headshot optimized for LinkedIn profiles and business networking."}', ARRAY['headshot']),
('Resume / CV', 'Purpose', '{"type": "Text", "description": "Formal, professional portrait suitable for job applications and professional documents."}', ARRAY['headshot']),
('Social Media Avatar', 'Purpose', '{"type": "Text", "description": "Engaging, personality-driven portrait optimized for social media platforms."}', ARRAY['headshot']),
('Dating App Look', 'Purpose', '{"type": "Text", "description": "Authentic, friendly portrait that captures personality while maintaining professionalism."}', ARRAY['headshot']),
('Actor / Talent Portfolio', 'Purpose', '{"type": "Text", "description": "Versatile headshot that showcases range and character for casting purposes."}', ARRAY['headshot']),
('Corporate ID', 'Purpose', '{"type": "Text", "description": "Standardized, professional portrait for company directories and internal communications."}', ARRAY['headshot']),
('Creative Portfolio Bio', 'Purpose', '{"type": "Text", "description": "Artistic, personality-driven portrait that reflects creative profession and style."}', ARRAY['headshot']),
('Influencer / Creator Profile', 'Purpose', '{"type": "Text", "description": "Engaging, brand-aligned portrait that connects with target audience."}', ARRAY['headshot']),
('Press Kit Headshot', 'Purpose', '{"type": "Text", "description": "High-quality, media-ready portrait for press releases and public relations."}', ARRAY['headshot']),
('Academic / Researcher Portrait', 'Purpose', '{"type": "Text", "description": "Professional, intellectual portrait suitable for academic profiles and publications."}', ARRAY['headshot']),

-- Headshot Clothing presets
INSERT INTO presets (name, category, content, modes) VALUES
('Classic Blazer', 'Clothing', '{"type": "Text", "description": "Professional blazer that adds structure and authority to the portrait."}', ARRAY['headshot']),
('Button-Up Shirt (Collared)', 'Clothing', '{"type": "Text", "description": "Traditional collared shirt for a clean, professional look."}', ARRAY['headshot']),
('Turtleneck Sweater', 'Clothing', '{"type": "Text", "description": "Elegant turtleneck that creates a sophisticated, timeless appearance."}', ARRAY['headshot']),
('Crew Neck T-Shirt', 'Clothing', '{"type": "Text", "description": "Simple, casual crew neck for a relaxed yet put-together look."}', ARRAY['headshot']),
('V-Neck Shirt', 'Clothing', '{"type": "Text", "description": "Flattering V-neck that elongates the neck and adds subtle sophistication."}', ARRAY['headshot']),
('Polo Shirt', 'Clothing', '{"type": "Text", "description": "Smart-casual polo that balances professionalism with comfort."}', ARRAY['headshot']),
('Business Suit (Tie Optional)', 'Clothing', '{"type": "Text", "description": "Formal business attire for maximum professional impact."}', ARRAY['headshot']),
('Casual Hoodie', 'Clothing', '{"type": "Text", "description": "Relaxed hoodie for a casual, approachable appearance."}', ARRAY['headshot']),
('Denim Jacket', 'Clothing', '{"type": "Text", "description": "Stylish denim jacket that adds a contemporary edge."}', ARRAY['headshot']),
('Leather Jacket', 'Clothing', '{"type": "Text", "description": "Edgy leather jacket for a bold, confident look."}', ARRAY['headshot']),
('Sweater Cardigan', 'Clothing', '{"type": "Text", "description": "Comfortable cardigan that adds warmth and texture."}', ARRAY['headshot']),
('High-Neck Blouse', 'Clothing', '{"type": "Text", "description": "Elegant high-neck blouse for a refined, professional appearance."}', ARRAY['headshot']),
('Off-Shoulder Top', 'Clothing', '{"type": "Text", "description": "Stylish off-shoulder top that adds a touch of femininity and flair."}', ARRAY['headshot']),
('Graphic Tee', 'Clothing', '{"type": "Text", "description": "Casual graphic tee that showcases personality and style."}', ARRAY['headshot']),
('Formal Dress (Solid Color)', 'Clothing', '{"type": "Text", "description": "Elegant solid-color dress for a sophisticated, professional look."}', ARRAY['headshot']),
('Patterned Shirt (Plaid / Stripes)', 'Clothing', '{"type": "Text", "description": "Patterned shirt that adds visual interest while maintaining professionalism."}', ARRAY['headshot']),
('Vest Over Shirt', 'Clothing', '{"type": "Text", "description": "Layered vest and shirt combination for a smart, put-together look."}', ARRAY['headshot']),
('Zippered Bomber Jacket', 'Clothing', '{"type": "Text", "description": "Modern bomber jacket that adds a contemporary, urban edge."}', ARRAY['headshot']),
('Long-Sleeve Henley', 'Clothing', '{"type": "Text", "description": "Casual yet refined henley shirt for a relaxed professional look."}', ARRAY['headshot']),
('Minimalist Tank Top', 'Clothing', '{"type": "Text", "description": "Simple tank top for a clean, minimalist appearance."}', ARRAY['headshot']);

-- Delete all headshot mode presets
DELETE FROM public.presets WHERE 'headshot' = ANY(modes); 