-- Insert material presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Metallic', 'Material', 'Shiny, reflective surface with metallic properties and specular highlights'),
    ('Glass', 'Material', 'Transparent or translucent surface with refractive properties and reflections'),
    ('Marble', 'Material', 'Natural stone with veined patterns and polished surface'),
    ('Wood', 'Material', 'Natural organic material with grain patterns and warm tones'),
    ('Stone', 'Material', 'Natural mineral surface with rough texture and earthy tones'),
    ('Leather', 'Material', 'Treated animal hide with distinctive grain and supple texture'),
    ('Fur', 'Material', 'Soft, fibrous material with depth and volume'),
    ('Silk', 'Material', 'Lustrous, smooth fabric with subtle sheen and drape'),
    ('Velvet', 'Material', 'Luxurious fabric with dense pile and light-absorbing properties'),
    ('Plastic', 'Material', 'Synthetic material with smooth surface and uniform properties'),
    ('Rubber', 'Material', 'Elastic material with matte finish and flexible properties'),
    ('Fabric', 'Material', 'Woven or knitted material with texture and drape'),
    ('Denim', 'Material', 'Durable cotton twill with distinctive diagonal ribbing'),
    ('Cotton', 'Material', 'Natural fiber with soft texture and matte finish'),
    ('Linen', 'Material', 'Natural fiber with crisp texture and subtle sheen'),
    ('Wool', 'Material', 'Natural fiber with crimped texture and insulating properties'),
    ('Clay', 'Material', 'Natural earth material with smooth, moldable properties'),
    ('Concrete', 'Material', 'Composite material with rough texture and industrial appearance'),
    ('Brick', 'Material', 'Fired clay material with porous surface and warm tones'),
    ('Sand', 'Material', 'Granular material with fine texture and natural color variations'),
    ('Snow', 'Material', 'Crystalline material with soft, reflective properties'),
    ('Ice', 'Material', 'Transparent crystalline material with refractive properties'),
    ('Crystal', 'Material', 'Clear mineral with geometric structure and light refraction'),
    ('Diamond', 'Material', 'Hard, transparent crystal with high refractive index'),
    ('Gold', 'Material', 'Precious metal with warm, reflective properties'),
    ('Silver', 'Material', 'Precious metal with cool, reflective properties'),
    ('Copper', 'Material', 'Metal with warm, reddish tones and patina potential'),
    ('Rusted Metal', 'Material', 'Oxidized metal with rough texture and reddish-brown tones'),
    ('Burnished Bronze', 'Material', 'Polished copper alloy with warm, reflective surface'),
    ('Glossy Finish', 'Material', 'Highly reflective surface with sharp highlights'),
    ('Matte Finish', 'Material', 'Non-reflective surface with soft, even appearance'),
    ('Polished Stone', 'Material', 'Smooth, reflective stone surface with natural patterns'),
    ('Weathered Texture', 'Material', 'Aged surface with natural wear and patina'),
    ('Grunge Texture', 'Material', 'Distressed surface with irregular patterns and wear'),
    ('Iridescent', 'Material', 'Surface that shifts colors based on viewing angle'),
    ('Holographic', 'Material', 'Surface that creates rainbow-like spectral effects'); 