-- Insert creative presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Inverted Gravity', 'Creative', 'Floating elements, upside-down structures, and surreal physics defying natural laws'),
    ('Time Warp', 'Creative', 'Motion blur trails, light speed effects, and bending space creating temporal distortion'),
    ('Melted Reality', 'Creative', 'Dali-style melting forms and surreal dreamscape with fluid, organic shapes'),
    ('Double Exposure', 'Creative', 'Two distinct scenes merged over each other creating layered, ghostly effects'),
    ('X-Ray Vision', 'Creative', 'See-through objects revealing internal structures and hidden details'),
    ('Hologram Look', 'Creative', 'Transparent light projections and sci-fi UI elements with ethereal glow'),
    ('Ink in Water', 'Creative', 'Soft diffusion, fluid movement, and abstract shapes creating organic patterns'),
    ('Glitch Effect', 'Creative', 'Digital distortion, color splits, and pixel artifacts creating technological disruption'),
    ('VHS Tape Look', 'Creative', 'Static lines, analog noise, and retro TV feel with vintage aesthetic'),
    ('Infrared Vision', 'Creative', 'Heatmap colors and false-color spectrum revealing thermal patterns'),
    ('Scanlines', 'Creative', 'Horizontal lines across image creating classic CRT screen aesthetic'),
    ('Fractal Style', 'Creative', 'Recursive patterns and mathematical repetition creating infinite detail'),
    ('AI Overpaint', 'Creative', 'Painterly remixing and AI-dreamlike layering creating surreal transformations'),
    ('Datamosh Effect', 'Creative', 'Corrupted frame blending and movement glitches creating digital distortion'),
    ('Surreal Collage', 'Creative', 'Mix of unrelated objects arranged with dream logic creating unexpected combinations'),
    ('Ink Sketch', 'Creative', 'Fine black lines and monochrome ink style creating elegant linework'),
    ('Crayon Drawing', 'Creative', 'Rough texture and childlike or playful look with expressive marks'),
    ('Low-Res Style', 'Creative', 'Low resolution and pixelated edges creating retro gaming aesthetic'),
    ('Low Poly', 'Creative', 'Minimal polygons and clean low-res style for stylized, geometric art'),
    ('Sketchy Style', 'Creative', 'Loose lines and sketchbook style with unrefined, energetic details'),
    ('Soft Focus', 'Creative', 'Intentionally soft or dreamy look with reduced sharpness and atmospheric quality'),
    ('Standard Detail', 'Creative', 'Normal visual quality without emphasis on resolution or special effects'),
    ('HD Quality', 'Creative', 'High detail, sharp edges, and well-defined forms for clear presentation'),
    ('4K Render', 'Creative', 'Ultra high definition with clean detail and cinematic polish'),
    ('8K Ultra Detail', 'Creative', 'Extreme detail and hyperrealistic quality with visible fine textures'),
    ('Photorealistic', 'Creative', 'Real-world texture, depth, shadows, and camera realism for lifelike quality'),
    ('Studio Quality', 'Creative', 'Professional studio lighting, crisp resolution, and commercial-grade polish'),
    ('Psychedelic Colors', 'Creative', 'Vibrant, warped color palettes creating trippy, mind-bending visuals'),
    ('Pop Art Style', 'Creative', 'Comic-like halftones, bold color blocks, and flat shading for graphic impact'),
    ('AI Abstraction', 'Creative', 'Machine-logic geometry and non-human arrangement creating algorithmic art'); 