-- Insert environment presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Cyberpunk City', 'Environment', 'Neon-lit urban landscape with towering skyscrapers and futuristic technology'),
    ('Futuristic Metropolis', 'Environment', 'Advanced cityscape with flying vehicles and holographic displays'),
    ('Post-Apocalyptic Wasteland', 'Environment', 'Desolate landscape with ruins and remnants of civilization'),
    ('Fantasy Forest', 'Environment', 'Magical woodland with glowing plants and mythical creatures'),
    ('Alien Planet', 'Environment', 'Exotic extraterrestrial landscape with unusual flora and fauna'),
    ('Underwater World', 'Environment', 'Submerged environment with coral reefs and marine life'),
    ('Medieval Village', 'Environment', 'Historic settlement with thatched roofs and cobblestone streets'),
    ('Steampunk City', 'Environment', 'Victorian-era city with steam-powered technology and brass machinery'),
    ('Desert Landscape', 'Environment', 'Vast arid terrain with sand dunes and rock formations'),
    ('Snowy Mountain Range', 'Environment', 'Majestic peaks covered in snow and ice'),
    ('Haunted House', 'Environment', 'Eerie mansion with gothic architecture and supernatural elements'),
    ('Space Station', 'Environment', 'Orbital facility with zero-gravity environments and advanced technology'),
    ('Tropical Beach', 'Environment', 'Paradise coastline with palm trees and crystal-clear water'),
    ('Ancient Ruins', 'Environment', 'Crumbling structures from a lost civilization'),
    ('Urban Street Scene', 'Environment', 'Busy city street with diverse architecture and activity'),
    ('Rainy Cityscape', 'Environment', 'Urban environment with wet streets and reflective surfaces'),
    ('Lush Jungle', 'Environment', 'Dense tropical forest with vibrant vegetation and wildlife'),
    ('Dystopian City', 'Environment', 'Oppressive urban environment with surveillance and decay'),
    ('Magical Castle', 'Environment', 'Enchanted fortress with mystical elements and grandeur'),
    ('Volcanic Landscape', 'Environment', 'Dramatic terrain with lava flows and volcanic features'),
    ('Deep Space', 'Environment', 'Cosmic void with distant stars and nebulae'),
    ('Futuristic Laboratory', 'Environment', 'Advanced research facility with cutting-edge technology'),
    ('Enchanted Garden', 'Environment', 'Magical botanical space with glowing plants and mystical creatures'),
    ('Frozen Tundra', 'Environment', 'Vast icy plains with sparse vegetation and extreme conditions'),
    ('Suburban Neighborhood', 'Environment', 'Residential area with manicured lawns and family homes'),
    ('Abandoned Factory', 'Environment', 'Industrial complex in decay with rust and overgrowth'),
    ('Mystical Cave', 'Environment', 'Underground cavern with glowing crystals and ancient carvings'),
    ('Sky City', 'Environment', 'Floating metropolis with cloud-based architecture'),
    ('Savannah Plains', 'Environment', 'Grassland ecosystem with scattered trees and wildlife'),
    ('Urban Rooftop', 'Environment', 'Cityscape view from above with architectural details'),
    ('Futuristic Highway', 'Environment', 'Advanced transportation network with flying vehicles'),
    ('Alien Jungle', 'Environment', 'Exotic forest with unusual plant life and creatures'),
    ('Gothic Cathedral', 'Environment', 'Grand religious structure with intricate architecture'),
    ('Floating Island', 'Environment', 'Suspended landmass with waterfalls and unique ecosystem'),
    ('Mars Colony', 'Environment', 'Human settlement on the red planet with domed habitats'),
    ('Ancient Temple', 'Environment', 'Sacred structure with historical significance and mystery'),
    ('Urban Alleyway', 'Environment', 'Narrow city passage with urban character and atmosphere'),
    ('Sunset Over Ocean', 'Environment', 'Coastal view with dramatic sky and water reflections'),
    ('Rainforest Canopy', 'Environment', 'Upper layer of tropical forest with diverse life'),
    ('Futuristic Arena', 'Environment', 'Advanced sports or entertainment venue with holographic displays'),
    ('Subterranean Cavern', 'Environment', 'Underground chamber with unique geological formations'),
    ('Abandoned Amusement Park', 'Environment', 'Former entertainment venue in decay with nostalgic elements'),
    ('Urban Subway Station', 'Environment', 'Underground transportation hub with urban atmosphere'),
    ('Fantasy Battlefield', 'Environment', 'Epic combat scene with magical elements and dramatic lighting'),
    ('Urban Park', 'Environment', 'Green space in the city with recreational features'),
    ('Futuristic Skyscraper', 'Environment', 'Advanced high-rise building with innovative design'),
    ('Ancient Library', 'Environment', 'Historic repository of knowledge with grand architecture'),
    ('Urban Marketplace', 'Environment', 'Busy commercial area with diverse vendors and activity'),
    ('Futuristic Spaceport', 'Environment', 'Advanced facility for spacecraft with modern technology'),
    ('Urban Bridge at Night', 'Environment', 'Illuminated city bridge with dramatic lighting and reflections'); 