-- Insert style presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Studio Ghibli', 'Style', 'Studio Ghibli style animation with soft colors, detailed backgrounds, and whimsical characters'),
    ('Cartoon', 'Style', 'Classic cartoon style with bold outlines, vibrant colors, and exaggerated features'),
    ('Photorealistic', 'Style', 'Ultra-realistic rendering with high detail, accurate lighting, and natural textures'),
    ('Anime', 'Style', 'Japanese animation style with expressive characters, dynamic poses, and stylized features'),
    ('Pixar', 'Style', 'Modern 3D animation style with smooth surfaces, expressive characters, and vibrant colors'),
    ('Disney Classic', 'Style', 'Traditional Disney animation style with hand-drawn charm and timeless appeal'),
    ('Disney Modern', 'Style', 'Contemporary Disney animation style with 3D rendering and modern character design'),
    ('Realism', 'Style', 'Naturalistic style focusing on accurate representation and lifelike details'),
    ('Oil Painting', 'Style', 'Traditional oil painting style with rich textures, visible brushstrokes, and depth'),
    ('Watercolor', 'Style', 'Soft, transparent watercolor style with flowing colors and gentle blending'),
    ('Pencil Sketch', 'Style', 'Hand-drawn pencil sketch style with visible lines and shading'),
    ('Cyberpunk', 'Style', 'High-tech, low-life aesthetic with neon lights, urban decay, and futuristic elements'),
    ('Steampunk', 'Style', 'Victorian-era industrial aesthetic with brass, gears, and steam-powered technology'),
    ('Fantasy', 'Style', 'Magical and mythical style with imaginative creatures and environments'),
    ('Dark Fantasy', 'Style', 'Gothic fantasy style with dark themes, dramatic lighting, and ominous atmosphere'),
    ('Surrealism', 'Style', 'Dreamlike style with unexpected combinations and impossible scenarios'),
    ('Hyperrealism', 'Style', 'Extremely detailed realism that appears more real than reality'),
    ('Impressionism', 'Style', 'Focus on light and atmosphere with visible brushstrokes and vibrant colors'),
    ('Minimalism', 'Style', 'Simple, clean design with minimal elements and maximum impact'),
    ('Chibi', 'Style', 'Super-deformed anime style with exaggerated cuteness and simplified features'),
    ('Gothic', 'Style', 'Dark, medieval-inspired aesthetic with ornate details and dramatic lighting'),
    ('Art Nouveau', 'Style', 'Organic, flowing decorative style with natural forms and elegant curves'),
    ('Art Deco', 'Style', 'Geometric patterns and luxurious ornamentation with bold colors'),
    ('Pop Art', 'Style', 'Bold colors and popular culture imagery with graphic design elements'),
    ('Looney Tunes', 'Style', 'Classic cartoon style with exaggerated expressions and slapstick humor'),
    ('Manga', 'Style', 'Japanese comic art style with dynamic layouts and expressive characters'),
    ('Shōnen', 'Style', 'Action-oriented manga style with dynamic poses and intense expressions'),
    ('Shōjo', 'Style', 'Romantic manga style with delicate features and emotional expressions'),
    ('Mecha', 'Style', 'Japanese robot and mechanical design style with detailed technology'),
    ('Kawaii', 'Style', 'Japanese cute style with round shapes, pastel colors, and adorable features'),
    ('Conceptual Art', 'Style', 'Idea-driven art style focusing on concepts and meaning'),
    ('Digital Painting', 'Style', 'Modern digital art style with painterly techniques and effects'),
    ('Graffiti', 'Style', 'Urban street art style with bold colors and stylized lettering'),
    ('Spray Paint', 'Style', 'Aerosol art style with spray effects and urban aesthetic'),
    ('Charcoal Drawing', 'Style', 'Rich, dark charcoal style with strong contrast and texture'),
    ('Ink Illustration', 'Style', 'Clean line art style with precise inking and cross-hatching'),
    ('Pastel Art', 'Style', 'Soft, powdery pastel style with gentle colors and blending'),
    ('Mixed Media', 'Style', 'Combination of different artistic mediums and techniques'),
    ('Collage', 'Style', 'Assembled artwork style combining various materials and images'),
    ('Mosaic', 'Style', 'Patterned style created from small pieces of colored material'),
    ('Cubism', 'Style', 'Geometric fragmentation of subjects with multiple viewpoints'),
    ('Expressionism', 'Style', 'Emotional and dramatic distortion with bold colors'),
    ('Abstract Expressionism', 'Style', 'Non-representational art with emotional intensity'),
    ('Dadaism', 'Style', 'Avant-garde style challenging conventional art norms'),
    ('Fauvism', 'Style', 'Bold, non-naturalistic colors with simplified forms'),
    ('Noir', 'Style', 'Dark, dramatic style with high contrast and moody lighting'),
    ('Mythological', 'Style', 'Ancient myths and legends style with classical elements'),
    ('Dreamlike', 'Style', 'Surreal, ethereal style with soft focus and magical elements'),
    ('Psychedelic', 'Style', 'Vibrant, mind-bending patterns with intense colors'),
    ('Whimsical', 'Style', 'Playful, fanciful style with imaginative elements'),
    ('Vintage Photography', 'Style', 'Classic photographic style with aged effects'),
    ('Black & White', 'Style', 'Monochrome style with strong contrast and composition'),
    ('Cinematic', 'Style', 'Movie-like composition with dramatic lighting and framing'),
    ('HDR', 'Style', 'High dynamic range with enhanced contrast and detail'),
    ('Macro Photography', 'Style', 'Extreme close-up style with detailed textures'),
    ('Tilt-Shift', 'Style', 'Miniature effect style with selective focus'),
    ('Street Photography', 'Style', 'Candid, documentary style capturing urban life'),
    ('Landscape Photography', 'Style', 'Natural scenery with emphasis on composition'),
    ('Portrait Photography', 'Style', 'Focused on capturing character and expression'),
    ('Long Exposure', 'Style', 'Motion blur effects with extended shutter times'),
    ('Aerial Photography', 'Style', 'Bird''s-eye view style with unique perspectives'),
    ('Astrophotography', 'Style', 'Celestial photography with stars and space elements'),
    ('Drone Photography', 'Style', 'Aerial views with modern drone technology'),
    ('Underwater Photography', 'Style', 'Aquatic environment style with water effects'),
    ('Webtoon', 'Style', 'Digital comic style optimized for web viewing'),
    ('Comic Book Style', 'Style', 'Traditional comic book art with panels and speech bubbles'),
    ('Superhero Comic', 'Style', 'Dynamic superhero comic style with action poses'),
    ('Shōnen Jump', 'Style', 'Popular manga magazine style with energetic characters'),
    ('Biopunk', 'Style', 'Biological technology aesthetic with organic elements'),
    ('Dieselpunk', 'Style', 'Retro-futuristic style based on diesel technology'),
    ('Post-Apocalyptic', 'Style', 'World after disaster with ruined environments'),
    ('Utopian', 'Style', 'Idealized future with perfect society and technology'),
    ('Dystopian', 'Style', 'Dark future with oppressive society and technology'),
    ('Symbolism', 'Style', 'Artistic style using symbols to represent ideas'),
    ('Rococo', 'Style', 'Ornate, decorative style with pastel colors and curves'),
    ('Baroque', 'Style', 'Dramatic, ornate style with strong contrast and movement'),
    ('Neo-Classicism', 'Style', 'Classical revival style with clean lines and symmetry'),
    ('Constructivism', 'Style', 'Geometric abstract style with industrial elements'),
    ('Op Art', 'Style', 'Optical illusion style with geometric patterns'),
    ('Pointillism', 'Style', 'Images created from small dots of pure color'),
    ('Etching', 'Style', 'Intaglio printmaking style with fine lines and texture'),
    ('Lithography', 'Style', 'Printmaking style with smooth surfaces and gradations'),
    ('Woodcut', 'Style', 'Relief printmaking style with bold, graphic quality'),
    ('Tempera', 'Style', 'Traditional painting style with egg-based medium'),
    ('Papercraft', 'Style', 'Art style resembling paper cutouts and origami'),
    ('Documentary Style', 'Style', 'Realistic, journalistic style capturing truth'),
    ('Time-Lapse', 'Style', 'Compressed time effect showing gradual changes'),
    ('Infrared Photography', 'Style', 'Specialized photography capturing infrared light'),
    ('Polaroid', 'Style', 'Instant film photography style with characteristic look'),
    ('Mixed Style (Fusion)', 'Style', 'Combination of multiple artistic styles'),
    ('Claymation', 'Style', 'Stop-motion animation style with clay figures'),
    ('3D Render', 'Style', 'Computer-generated imagery with depth and lighting'),
    ('Isometric', 'Style', 'Technical drawing style with equal measurements'),
    ('Pixel Art', 'Style', 'Digital art using visible pixels as building blocks'),
    ('Vector Art', 'Style', 'Clean, scalable graphics with precise lines'),
    ('Low Poly', 'Style', '3D style with minimal polygon count'),
    ('Line Art', 'Style', 'Artwork created with distinct lines and minimal shading'),
    ('Flat Design', 'Style', 'Minimalist design with two-dimensional elements'),
    ('Minimal Linework', 'Style', 'Simple line-based style with essential details'),
    ('Fashion Illustration', 'Style', 'Stylized drawing style for fashion design'); 