-- Insert lighting presets
INSERT INTO public.presets (name, category, content) VALUES
    ('Golden Hour', 'Lighting', 'Warm, soft lighting during sunrise or sunset with long shadows and golden tones'),
    ('Blue Hour', 'Lighting', 'Cool, soft lighting during twilight with deep blue tones and subtle shadows'),
    ('Sunlight', 'Lighting', 'Natural daylight with balanced exposure and natural shadows'),
    ('Moonlight', 'Lighting', 'Soft, cool lighting with gentle shadows and a silvery glow'),
    ('Starlight', 'Lighting', 'Subtle, twinkling light with deep shadows and a magical atmosphere'),
    ('Overcast Lighting', 'Lighting', 'Soft, diffused lighting with minimal shadows and even illumination'),
    ('Foggy Lighting', 'Lighting', 'Mysterious, diffused lighting with atmospheric depth and soft edges'),
    ('Rainy Lighting', 'Lighting', 'Wet, reflective lighting with dramatic atmosphere and water effects'),
    ('Snowy Lighting', 'Lighting', 'Bright, reflective lighting with crisp shadows and winter atmosphere'),
    ('Crepuscular Rays', 'Lighting', 'Dramatic light beams breaking through clouds or trees'),
    ('Rembrandt Lighting', 'Lighting', 'Classic portrait lighting with triangular highlight on cheek'),
    ('Loop Lighting', 'Lighting', 'Soft, flattering portrait lighting with small nose shadow'),
    ('Butterfly Lighting', 'Lighting', 'Portrait lighting with butterfly-shaped shadow under nose'),
    ('Broad Lighting', 'Lighting', 'Portrait lighting that illuminates the side of face closest to camera'),
    ('Short Lighting', 'Lighting', 'Portrait lighting that illuminates the side of face away from camera'),
    ('Split Lighting', 'Lighting', 'Dramatic lighting that splits the face into light and dark halves'),
    ('Rim Lighting', 'Lighting', 'Backlighting that creates a glowing outline around the subject'),
    ('Backlighting', 'Lighting', 'Light source behind the subject creating dramatic silhouettes'),
    ('Side Lighting', 'Lighting', 'Light coming from the side creating strong shadows and depth'),
    ('Top Lighting', 'Lighting', 'Light coming from above creating dramatic shadows'),
    ('Chiaroscuro', 'Lighting', 'Strong contrast between light and dark areas'),
    ('Noir Lighting', 'Lighting', 'Dramatic, high-contrast lighting with deep shadows'),
    ('Cinematic Lighting', 'Lighting', 'Professional film lighting with controlled shadows and highlights'),
    ('High-Key Lighting', 'Lighting', 'Bright, even lighting with minimal shadows'),
    ('Low-Key Lighting', 'Lighting', 'Dark, dramatic lighting with strong shadows'),
    ('Silhouette Lighting', 'Lighting', 'Backlit subject appearing as a dark shape against bright background'),
    ('Dappled Light', 'Lighting', 'Patterned light created by light passing through leaves or objects'),
    ('Volumetric Lighting', 'Lighting', 'Visible light beams creating a sense of depth and atmosphere'),
    ('Lens Flare', 'Lighting', 'Artistic light artifacts created by bright light sources'),
    ('Anamorphic Lighting', 'Lighting', 'Cinematic lighting with characteristic horizontal lens flares'),
    ('Neon Lighting', 'Lighting', 'Vibrant, colorful artificial lighting with glowing effects'),
    ('Iridescent Lighting', 'Lighting', 'Shifting, rainbow-like lighting effects'),
    ('Bioluminescent Lighting', 'Lighting', 'Natural glowing light from living organisms'),
    ('Holographic Lighting', 'Lighting', 'Futuristic, multi-dimensional lighting effects'),
    ('Prismatic Lighting', 'Lighting', 'Light broken into spectral colors through refraction'),
    ('Shimmering Light', 'Lighting', 'Sparkling, reflective lighting with dynamic highlights'),
    ('Glowing Translucency', 'Lighting', 'Soft, internal illumination of semi-transparent materials'),
    ('Specular Highlights', 'Lighting', 'Sharp, bright reflections on glossy surfaces'),
    ('Caustic Lighting', 'Lighting', 'Complex light patterns created by refraction through water or glass'),
    ('Subsurface Scattering', 'Lighting', 'Light passing through translucent materials creating soft glow'),
    ('Streetlight Illumination', 'Lighting', 'Urban night lighting with characteristic orange glow'),
    ('Candlelight', 'Lighting', 'Warm, flickering light from candle flames'),
    ('Firelight', 'Lighting', 'Dynamic, warm lighting from fire with dancing shadows'),
    ('Lantern Light', 'Lighting', 'Soft, contained light with gentle shadows'),
    ('Fluorescent Lighting', 'Lighting', 'Cool, artificial lighting with characteristic green tint'),
    ('Incandescent Lighting', 'Lighting', 'Warm, artificial lighting with soft shadows'),
    ('LED Lighting', 'Lighting', 'Modern, energy-efficient lighting with clean illumination'),
    ('Spotlight', 'Lighting', 'Focused, directional lighting with sharp edges'),
    ('Stage Lighting', 'Lighting', 'Professional theatrical lighting with dramatic effects'),
    ('Ambient Lighting', 'Lighting', 'General, overall illumination with soft shadows'); 