-- Insert color presets
INSERT INTO public.presets (name, category, content) VALUES
    ('High Contrast', 'Color', 'Dramatic color scheme with strong light-dark contrast and bold color separation'),
    ('Muted Colors', 'Color', 'Soft, desaturated color palette with subtle, understated tones'),
    ('Vibrant Colors', 'Color', 'Bright, saturated color scheme with intense, eye-catching hues'),
    ('Black and White', 'Color', 'Classic monochrome palette with pure black, white, and grayscale tones'),
    ('Sepia Tone', 'Color', 'Warm, vintage color scheme with brownish-yellow tint reminiscent of old photographs'),
    ('Cool Tone', 'Color', 'Color palette dominated by blue, green, and purple tones creating a calm atmosphere'),
    ('Warm Tone', 'Color', 'Color palette dominated by red, orange, and yellow tones creating a cozy atmosphere'),
    ('Analog Film Look', 'Color', 'Color scheme mimicking classic film photography with subtle color shifts'),
    ('Glowing Colors', 'Color', 'Luminous color scheme with bright, radiant hues and light emission effects'),
    ('Pastel Colors', 'Color', 'Soft, light color palette with low saturation and gentle tones'),
    ('Neon Colors', 'Color', 'Electric, fluorescent color scheme with intense, glowing hues'),
    ('Color Splash', 'Color', 'Selective color scheme with one or few colors highlighted against monochrome'),
    ('Monochromatic', 'Color', 'Color scheme using variations of a single hue with different saturations and values'),
    ('Duotone', 'Color', 'Two-color scheme creating dramatic contrast and visual impact'),
    ('Infrared Colors', 'Color', 'Surreal color scheme mimicking infrared photography with unusual color shifts'),
    ('Technicolor', 'Color', 'Vibrant, saturated color scheme reminiscent of classic Technicolor films'),
    ('Golden Hour', 'Color', 'Warm, golden color scheme mimicking the soft light of sunrise or sunset'),
    ('Tungsten Light', 'Color', 'Warm, orange-tinted color scheme mimicking tungsten light sources'),
    ('Daylight Cool', 'Color', 'Natural, balanced color scheme with slight blue tint for daylight scenes'),
    ('Underwater Tint', 'Color', 'Color scheme with blue-green tint and light diffusion effects'),
    ('Rustic Palette', 'Color', 'Earthy color scheme with natural, muted tones and vintage feel'),
    ('Vintage Print', 'Color', 'Color scheme mimicking aged prints with subtle color shifts and grain'),
    ('Iridescent', 'Color', 'Color scheme with shifting, rainbow-like effects based on viewing angle'),
    ('Cyberpunk Colors', 'Color', 'Futuristic color scheme with neon accents and dark, moody tones'),
    ('Flat Colors', 'Color', 'Clean, solid color scheme with minimal gradients and shadows'); 